### ISSUE TITLE
Nicht alle Rollen werden im Vote angezeigt

### ISSUE THREAD

**Issue by tobi-nb** [Blaubeeree/ttt2-rolevote#13]
Die folgenden Rollen sind auf meinem Server installiert:

![image](https://user-images.githubusercontent.com/54220297/106047321-c0989580-60e3-11eb-8ff2-9f4de52c2600.png)

Bei einem Vote sind aber nicht alle Rollen zur Abstimmung verfügbar, wie hier sichtbar:

![image](https://user-images.githubusercontent.com/54220297/106048338-0d30a080-60e5-11eb-9684-58b98c36e0f5.png)

Hier meine aktuellen Einstellungen:

![image](https://user-images.githubusercontent.com/54220297/106047799-592f1580-60e4-11eb-9a9b-f97ae155002b.png)

Gleichzeitig tritt hier auch ein 2. Fehler auf: Die theoretisch immer aktiven Rollen bleiben deaktiviert... Die Einstellungen siehst du ja im Screenshot. Vor allem Detective ist nicht aktiv, was ziemlich störend ist. Auch Großschreibung hat nichts geändert.

**Comment by Blaubeeree** [comment]
Du hast den cooldown auf 1 gestellt, das heist rollen die ein vote gewonnen haben sind erst beim übernächsten vote wieder dabei, das könnte das problem sein.
Was die always active roles angeht muss ich nochmal schauen, kannst du mir sagen ob es irgendwelche errors in der console gibt?

**Comment by tobi-nb** [comment]
Oh man, na klar, sorry xD 
Die einzigen Errors, die ich bisher hatte, waren die Folgenden:

[ERROR] lua/autorun/client/cl_rolevote_networking.lua:16: attempt to index field 'vgui' (a nil value)
  1. func - lua/autorun/client/cl_rolevote_networking.lua:16
   2. unknown - lua/includes/extensions/net.lua:32


[ZΣNAJ|17|STEAM_0:0:42024334] Lua Error:

[ERROR] lua/autorun/client/cl_rolevote_networking.lua:16: attempt to index field 'vgui' (a nil value)
  1. func - lua/autorun/client/cl_rolevote_networking.lua:16
   2. unknown - lua/includes/extensions/net.lua:32


[ZΣNAJ|17|STEAM_0:0:42024334] Lua Error:

[ERROR] lua/autorun/client/cl_rolevote_networking.lua:16: attempt to index field 'vgui' (a nil value)
  1. func - lua/autorun/client/cl_rolevote_networking.lua:16
   2. unknown - lua/includes/extensions/net.lua:32

Aber sonst kamen keine Error. Ich bin nicht gut in Lua und kenn mich nicht mit dem Aufbau von Addons aus, aber was für Rollennamen benötigt das Addon denn? Und sind die Namen case-sensitive? 

Workshop-Collection des Servers: https://steamcommunity.com/sharedfiles/filedetails/?id=849222406

**Comment by Blaubeeree** [comment]
Die namen sind nicht case sensitive, es sind die ganz normalen (englischen) Namen der Rollen und die standart Rollen Dete, Inno Und T sind immer aktiv (weil es sonst fehler mit anderen Rollen geben würde).
Das es bei dir gerade nicht funktioniert ist ein Bug aus dem Update von heute, ich mach schnell einen fix dafür

**Comment by Blaubeeree** [comment]
should be fixed now, the workshop will be updated in a few minutes
