### ISSUE TITLE
Rollen durch ConVars zur Abstimmung freigeben

### ISSUE THREAD

**Issue by tobi-nb** [Blaubeeree/ttt2-rolevote#14]
Es wäre super, wenn Rolevote nur Rollen zum Abstimmen anzeigen würde, die für diese aktuelle Spieleranzahl verfügbar sind. 

Als Beispiel: Necromancer wird ab 5 Spielern aktiv, Wrath ab 7. Aktuell ist man gezwungen, entweder alle Rollen ab der selben Spieleranzahl zu aktivieren oder den RoleVote auf 7 zu setzen. Setze ich die Mindestanzahl beim RoleVote jetzt auf 5 Spieler, wäre sowohl Necromancer als auch Wrath zur Abstimmung verfügbar. 

Wenn RoleVote die gesetzten ConVars der installierten Rollen ausliest und dann auch nur bei der Mindestanzahl der Spieler zur Abstimmung freigibt, das wäre perfekt :D 

Und btw: ch find dein Addon richtig nice, bringt frischen Wind auf den Server und ist echt mal was Neues :D

**Comment by Blaubeeree** [comment]
Das Problem damit wäre das die Abstimmung (wenn man sie nicht manuel über ulx startet) sofort nach mapwechsel beginnt sobalt genug Spieler da sind und das Addon weis nicht wie viele noch bis Rundenanfang dazu kommen, heißt nur die Rollen die zu dem Zeitpunkt aktiv sind wären im Vote.
Was noch kommt ist eine Anzeige ab wie viel Spielern eine Rolle aktiv wird (ich hab nur zur Zeit sehr viel privat zu tun weswegen die Updates nur sehr langsam kommen)

**Comment by tobi-nb** [comment]
Ich baller hier auch nur meine Ideen raus :D Ist ja auch nur ein Enhancement, nichts Essentielles. 
Ein Workaround wäre, beim Mapchange die Spieleranzahl zu speichern und danach wieder zu laden. Wäre nicht optimal, müsste aber funktionieren.

**Comment by Blaubeeree** [comment]
Das Problem ist bei Mapchange werden alle Addons neu geladen, ich müsste es wenn dann in der db abspeichern und einen Weg finden Mapchange von Serverstart zu unterscheiden. Also alles in allem sehr dirty und ich finde das mit der Anzeige der Mindestspieler für eine Rolle (aus #6 btw.) ist ein guter Kompromiss.
