### ISSUE TITLE
SetPlayer falscher Argumenttyp

### ISSUE THREAD

**Issue by tobi-nb** [Blaubeeree/ttt2-rolevote#15]
Bei einem Mapchange bekomme ich aktuell folgende Meldung:

```
[[TTT2] RoleVote] lua/autorun/client/cl_rolevote_vgui.lua:137: bad argument #1 to 'SetPlayer' (Entity expected, got boolean)
  1. SetPlayer - [C]:-1
   2. UpdateVotes - lua/autorun/client/cl_rolevote_vgui.lua:137
    3. func - lua/autorun/client/cl_rolevote_networking.lua:17
     4. unknown - lua/includes/extensions/net.lua:32
   ```

**Comment by Blaubeeree** [comment]
Wärend dem Mapchange (also bevor ein Spieler drauf ist und bevor `VAC secure mode is activated.` in der console kommt) oder danach?

**Comment by tobi-nb** [comment]
Nein, nachdem alles geladen wurde und der Spieler connected. Hier noch ein größerer Auszug der Log: https://pastebin.com/DhNYuJhi

**Comment by Blaubeeree** [comment]
Ich schaff es nicht den bug nachzustellen, liegt villeicht an irgendeinem anderen addon.
Geht alles noch oder macht der error irgendwas kaputt, weil es sieht nur nach einem Anzeigefehler aus?

**Comment by tobi-nb** [comment]
Also soweit ich weiß hat noch alles geklappt. Wenn ich das richtig sehe tritt das Problem auf, wenn genug Leute gejoint haben und gespawnt wurden und weitere Leute nach diesem Spawn betreten.  Nur für diese Leute, die nach der Spawn Wave den Server betreten haben, tritt der Fehler auf. Hier nochmal ein größerer Auszug der Log, da sollte das ersichtlich werden: https://pastebin.com/aGVAJvfx
Es könnte aber auch sein, dass dieser Fehler auftritt, da die entsprechenden Leute im Spectator-Modus waren, das werde ich nochmal beobachten. Hier ist nochmal ein anderer Auszug mit dem Fehler: https://pastebin.com/sqru5iS3

**Comment by Blaubeeree** [comment]
ich glaub ich hab den fehler gefunden, sollte mit 95e2906cef4f6ae313de2e79cfa341f0cea47a8e behoben sein
