### ISSUE TITLE
Ban Role Cooldown

### ISSUE THREAD

**Issue by sinsa92** [Blaubeeree/ttt2-rolevote#3]
Would be cool if there could be a cooldown for the banned roles. For example: If the Spy gets banned, it cant get banned again for a configurable amount of maps.

**Comment by Blaubeeree** [comment]
I was already working on this feature, it should be released in the next few days

**Comment by Blaubeeree** [comment]
Now implemented in last commit: 7900c2ebd92cc6c0d7b0daeea69d4fc5900063e9
