### ISSUE TITLE
Mid-Map

### ISSUE THREAD

**Issue by sinsa92** [Blaubeeree/ttt2-rolevote#4]
Rolevote Voting Panbel appears mid-map. Noone can Vote, Console throws following error: `[[TTT2] RoleVote] lua/autorun/client/cl_rolevote.lua:57: attempt to call method 'SetFont' (a nil value)
  1. DoClick - lua/autorun/client/cl_rolevote.lua:57
   2. unknown - lua/vgui/dlabel.lua:237 (x4)`

**Comment by Blaubeeree** [comment]
I need more infos: Did anything special happend befor the error? Where there any other errors (especially in the server console)?

**Comment by sinsa92** [comment]
No and No

**Comment by sinsa92** [comment]
Sobald ich als Executioner im Teamchat geschrieben habe und jemand gejoint ist, ist das menü 
gekommen.

**Comment by Blaubeeree** [comment]
should be fixed with e6d5477e7b284bb67fe0091d283267611b88b521

**Comment by Blaubeeree** [comment]
forgot to close the issue
