### ISSUE TITLE
Vorschlag: Technisch

### ISSUE THREAD

**Issue by smallerYeet** [Blaubeeree/ttt2-rolevote#5]
Ich habe gerade Role Vote zum ersten Mal benutzt und mir sind ein paar Sachen aufgefallen.

- [X] Ein gutes Feature wäre, wenn man Rollen als Perma-aktiv markieren kann. Würde sehr Praktisch sein um neben den 3 Rollen noch mehr als Default zu machen.

- [X] Das andere Technische wäre ein Force Vote. Ich spiele mit Freunden und habe auch nicht immer alle Bereit um eben minimal 5 Spieler (Meine Einstellung) zu erreichen, doch würde gerne was Testen. Damit würde es gehen.

Hoffe das ich alles gut erklärt habe und das es ok war in Deutsch zu schreiben.

(Habe noch eine Zweite issue mit UI related)

**Comment by Blaubeeree** [comment]
> Ein gutes Feature wäre, wenn man Rollen als Perma-aktiv markieren kann. Würde sehr Praktisch sein um neben den 3 Rollen noch mehr als Default zu machen.

Sollte jetzt funktionieren mit der neuen ConVar (eada379e32b05d9be100bfc3e8acaa2856b75326).
Ich bin in letzter Zeit leider ein bisschen langsam mit neuen Updates, da ich zur Zeit private viel zu tun hab.

**Comment by Blaubeeree** [comment]
Ist jetzt alles implementiert und im Workshop (cc829b2f2f534604e5281dd6de11ae0ec13c5ec4). Das UI Update kommt auch irgendwann. Danke für deine Hilfe.
