### ISSUE TITLE
Vorschlag: UI

### ISSUE THREAD

**Issue by smallerYeet** [Blaubeeree/ttt2-rolevote#6]
Hier wieder Vorschläge, nur diesmal eher aufs UI bezogen.
Ich habe keine Probleme wie es aussieht, ist auch eine Beta.

Da wir auf meinem Server nur wenige sind, wäre es gut eine minimale Spieleranzahl für die Rollen sichtbar zu machen. So könnte man ganz einfach sehen ob der Server überhaupt gerade imstande ist eine Rolle zu Spawnen.

Das zweite und auch letzte wäre mehr votes für einen Spieler. Der Satz sagt alles, wieder ist es wenn wenig Spieler da sind, dass man eben mehr votes hat. Kann vielleicht mit Spieler Down-scalen, doch wäre für kleine Server wie meiner sehr Praktisch (sicherlich auch für größere).

Das alles natürlich noch so, dass man es abschalten kann (oder einschalten) wenn man es nicht möchte.

Das war's so weit, noch einen schönen Morgen/Tag/Abend!

**Comment by Blaubeeree** [comment]
Ein vgui update ist schon geplant (dauert wahrscheinlich nur noch ein bisschen weil ich mich damit noch nie beschäftigt hab). Bei dem zweiten Vorschlag seh ich ein Problem: Was passiert wenn kurz vor Voteende noch ein spieler joint und man damit nur noch 1 statt 2 Votes hat?

**Comment by smallerYeet** [comment]
In der Theorie würde das bedeuten, dass eigentlich genügend Spieler da sind um eben alles gut zu Voten.
Kurz vorm Vote ende ist wirklich die andere Sache.
Ich denke es wird sich was finden, aber gerade weiß ich nichts

**Comment by Blaubeeree** [comment]
>Da wir auf meinem Server nur wenige sind, wäre es gut eine minimale Spieleranzahl für die Rollen sichtbar zu machen. So könnte man ganz einfach sehen ob der Server überhaupt gerade imstande ist eine Rolle zu Spawnen.

ist mit ba38973f140f749837fbebffb4a554ab1f388e65 umgesetzt 👍 (hat ja nur 2 jahre gebraucht xD)

>Das zweite und auch letzte wäre mehr votes für einen Spieler. Der Satz sagt alles, wieder ist es wenn wenig Spieler da sind, dass man eben mehr votes hat. Kann vielleicht mit Spieler Down-scalen, doch wäre für kleine Server wie meiner sehr Praktisch (sicherlich auch für größere).

hab erstmal nicht vor sowas umzusetzen, ich schließ diese issue lass aber mal #11 bei der das selbe vorgeschlagen wurde offen, villeicht hab ich wieder 2 jahre später mal lust was hier zu machen :D
